- CHANGELOG.md
- src/reader.rs
Closes #1. Currently any issues with UTF-8 decoding cause a panic, so this adds a fallback to `from_utf8_lossy` instead of calling `expect`
> Fix UTF-8 decoding errors

- src/writer.rs
Resolves a few Clippy warnings for `needless_borrow`
> Clean up clippy needless_borrow lints

- src/errors.rs
- src/reader.rs
- src/types/mod.rs
- src/types/style.rs
- src/types/vec2.rs
- src/writer.rs
> Added vec2type struct and unitstype enum; changed IconStyle hot_spot

- Cargo.toml
Bumps the version of `quick-xml`. Based on the [changelog](https://github.com/tafia/quick-xml/blob/master/Changelog.md) the breaking changes shouldn't impact the project
> build(deps): update quick-xml

- src/errors.rs
Closes #21.
This adds conditional compilation to the `ZipError` error variant so that it is only compiled with the _zip_ feature.
> fix: compilation failure without zip feature

- src/writer.rs
Changed write order on serialization for `extrude`, `tessellate` for `write_point()` and `extrude`, `tessellate`, `altitudeMode` for `write_geom_props` so that the result validates against http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd
> Serialization: Changed write order for extrude, tessellate, altitudeModeGroup

- .github/workflows/ci.yml
- src/lib.rs
- src/types/kml.rs
- src/types/point.rs
Adds running `cargo test` with `--no-default-features` to the CI test step, and splits out running `cargo bench` into its own job since it's not important there. This should prevent running into any issues like #21.
I had to update some of the doctests with `#[cfg]` but I'm commenting that out so that it doesn't show in the final documentation output.
Also includes two unrelated changes to reduce the amount of duplication in running CI (currently running on branch and PR for every PR made from a branch on this repo) and to make two links clickable that I ran into while testing `cargo doc` locally. These seemed pretty small and easiest to just incorporate here
Feedback is welcome! This should be a pretty minor fix as long as CI passes
> Run tests without default features in CI

- src/errors.rs
- src/reader.rs
- src/types/kml.rs
- src/types/link.rs
- src/types/mod.rs
- src/writer.rs
Attempt to add support for `kml:Link` and `kml:Icon`.
A couple of points to discuss.
Since the spec's `kml:Icon` (or `kml:BasicLinkType`) is already implemented and exported by the library as `Kml::Icon`, I used an enum to model the spec's `kml:LinkType`. Its variants are `Kml::Link` and `Kml:Icon`. Both are constructed with `kml::types::LinkModel`, the common data model used by the spec's `kml:LinkType`.
If `kml:Model` was to be implemented using this PR, then it's `link` field would be of type `kml::types::LinkType` and it would need to be guarded so as not to have it be set to `kml::types::LinkType::Icon`:
```rust
pub struct Model {
link: Option<kml::types::LinkType>,
// ...
}
impl Default for Model {
fn default() -> Model {
Model { link: None }
}
}
impl Model {
pub fn get_link(&self) …
```
> Add kml:Link, kml:Icon

- Cargo.toml
Running `cargo fix --edition` didn't produce any actual changes, but it seems worth updating the edition in `Cargo.toml` to reflect that in case a future edition does require changes
> Update edition to 2021

- src/reader.rs
- src/types/alias.rs
- src/types/kml.rs
- src/types/mod.rs
- src/types/resource_map.rs
- src/writer.rs
Support `kml:Alias` and `kml:ResourceMap` elements.
Closes #15.
> Add kml:Alias and kml:ResourceMap

- src/types/alias.rs
- src/types/altitude_mode.rs
- src/types/coord.rs
- src/types/kml.rs
- src/types/line_string.rs
- src/types/linear_ring.rs
- src/types/link.rs
- src/types/location.rs
- src/types/orientation.rs
- src/types/point.rs
- src/types/polygon.rs
- src/types/resource_map.rs
- src/types/scale.rs
- src/types/style.rs
- src/types/vec2.rs
Fix new clippy warnings introduced by stable Rust moving to 1.63.0.
Changes generated by `cargo clippy --fix` after upgrading to Rust 1.63.0.
> Fix clippy warnings

- src/writer.rs
It looks like I missed writing attributes out on a few elements where we're reading them in. I've added that in and cleaned up the implementation for writing attributes that are stored as their own fields as well as in the `attrs` `HashMap` on `SimpleData` and `SimpleArrayData`
Closes #37
> Fix missing attributes, support filtering

- CHANGELOG.md
- src/reader.rs
- src/types/style.rs
- src/writer.rs
Closes #39. Adds `attrs` to style elements to keep in line with spec. Also makes `id` optional to more accurately reflect the spec
This will be a small breaking change to the `id` fields along with adding the public `attrs` field on several elements
> Add attrs to style elements, make ID optional

- src/lib.rs
- src/types/altitude_mode.rs
- src/types/kml.rs
- src/types/link.rs
- src/types/style.rs
Removes temporary `#[allow(clippy::derivable_impls)]` and implements defaults on enum through 1.62+ rust `derive`.
> Fix default impl on enums

- Cargo.toml
Encrypted KMZ files are currently not supported (and possibly should never be supported?), therefore the default `aes-crypto` feature of `zip` can be disabled.
> Disable unneeded zip aes-crypto feature

- src/reader.rs
Hi,
this is just a quick fix for the IconStyle hotSpot parsing.
Was implemented as "hot_spot" but should be "hotSpot" according to https://developers.google.com/kml/documentation/kmlreference
I have tested the fix locally and the hotSpot is now correctly parsed.
Would be great if this could be included in the repo.
Cheers,
Adrian
> Fixed parsing of IconStyle hotSpot.

- src/types/style.rs
Closes #56 
Fixes the default `ColorMode` by making it `normal` instead of `default` to accurately match the specification
> fix: make default color mode normal

- .gitignore
- Cargo.toml
- src/errors.rs
- src/kmz_reader.rs
- src/reader.rs
- tests/fixtures/style-merging.kml
- tests/test_roundtrip.rs
> Support comments

- src/reader.rs
According to the Google KML docs, a Polygon is allowed to have "0 or more inner boundaries".
[Source](https://developers.google.com/kml/documentation/kmlreference#polygon)
In the current parser, the LinearRings within an `innerBoundaryIs` tags are assigned to the `inner` field of a parsed Polygon. However, if multiple `innerBoundaryIs` tags are present, only the last is currently assigned to the `inner` field of the Polygon. The proposed change appends output from `innerBoundaryIs` tags so that consecutive tags don't overwrite each other.
I created a small reproduction of this issue in a separate repo:
- Crate: https://github.com/cfzimmerman/kml_inner_boundary_repro/tree/main
- Here's an example of a file with data loss: https://github.com/cfzimmerman/kml_inner_boundary_repro/blob/main/inn …
> fix: allow cumulative innerBoundaryIs tags on a polygon

- src/reader.rs
- src/types/placemark.rs
- src/writer.rs
Google Earth does add `styleUrl` to Placemark but it wasn't supported.  Fix it.
> Add styleUrl to Placemark.

- README.md
- src/conversion.rs
- src/lib.rs
Following what was done in [geojson](https://github.com/georust/geojson/blob/main/CHANGES.md#unreleased) and replacing the separate `quick_collection` method with an implementation of `TryFrom` for `geo_types::GeometryCollection`
> Deprecate quick collection for TryFrom

- src/conversion.rs
- src/reader.rs
- src/types/folder.rs
- src/types/kml.rs
- src/types/mod.rs
- src/writer.rs
- Usually called `CHANGES.md` or `CHANGELOG.md`
- Prefix changelog entries for breaking changes with "BREAKING: "
---
Added support for a nam, description, and styleUrl, and cleaned it up into a new `Folder` type. The new type does not fully implement the entire structure defined by ogc, https://docs.ogc.org/is/12-007r2/12-007r2.html#241
> Add name, description, and styleUrl support for Folder

- src/reader.rs
Update folder parsing to use the general `read_elements` method to parse it's children, and then filter that list to identify the specific elements that can be used as attributes.
This fixes a bug where previously all other elements that were children of `Folder` were getting parsed into `Kml::Element` even if they were known data types.
Closes #66
> fix: folder sub element parsing

- src/reader.rs
- Usually called `CHANGES.md` or `CHANGELOG.md`
- Prefix changelog entries for breaking changes with "BREAKING: "
---
This change allows the parsing of `kml` files with empty `coordinates` (this can be checked on client code):
```xml
<?xml version="1.0" encoding="utf-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>
<Placemark>
<name>test</name>
<LineString>
<altitudeMode>absolute</altitudeMode>
<coordinates />
</LineString>
</Placemark>
</Document>
</kml>
```
I have customers provided `kml` files with some valid `Placemark` and some invalid (empty coordinates like in the example). 
Right now I cannot parse the file because it return an error for empty `coordinates` but this can be safely checked inside client code.
> Don't fail parsing on empty coordinates

- src/reader.rs
- src/types/data.rs
- src/types/kml.rs
- src/types/mod.rs
- src/writer.rs
- Usually called `CHANGES.md` or `CHANGELOG.md`
- Prefix changelog entries for breaking changes with "BREAKING: "
---
fixes https://github.com/georust/kml/issues/32
kml:Data contains some attrs, so i added new method for ordering them ( im not sure about the need it, i didn't find anything similar in the code )
i dont know about < kml:DataExtension >…</kml:DataExtension>, in documentation i didn't find enough information  to add support for it
> Add kml:Data
